// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqS71bDoafAvR-l6LQVAdFqI-i5vwI8po',
    appId: '1:448005571837:web:67c76ddc705f722d106a94',
    messagingSenderId: '448005571837',
    projectId: 'tugas-akhir-f9264',
    authDomain: 'tugas-akhir-f9264.firebaseapp.com',
    databaseURL:
        'https://tugas-akhir-f9264-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-akhir-f9264.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsGf--CJVAdi1itcCjO8ntcUOGFzThHkw',
    appId: '1:448005571837:android:255770e317890194106a94',
    messagingSenderId: '448005571837',
    projectId: 'tugas-akhir-f9264',
    databaseURL:
        'https://tugas-akhir-f9264-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-akhir-f9264.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPcjzSdlNoZJYkA6eBPdAVkBH5_YVPj1U',
    appId: '1:448005571837:ios:f65535fe6ac6f908106a94',
    messagingSenderId: '448005571837',
    projectId: 'tugas-akhir-f9264',
    databaseURL:
        'https://tugas-akhir-f9264-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-akhir-f9264.appspot.com',
    iosClientId:
        '448005571837-evdj636rcf5tthkmfrcfqmktdgk5g22s.apps.googleusercontent.com',
    iosBundleId: 'com.example.simohin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPcjzSdlNoZJYkA6eBPdAVkBH5_YVPj1U',
    appId: '1:448005571837:ios:f65535fe6ac6f908106a94',
    messagingSenderId: '448005571837',
    projectId: 'tugas-akhir-f9264',
    databaseURL:
        'https://tugas-akhir-f9264-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugas-akhir-f9264.appspot.com',
    iosClientId:
        '448005571837-evdj636rcf5tthkmfrcfqmktdgk5g22s.apps.googleusercontent.com',
    iosBundleId: 'com.example.simohin',
  );
}
